<?xml version="1.0" encoding="utf-8" ?>
<!--外部dtd-->
<!DOCTYPE students SYSTEM "D:\DW_note\java\javaEE\4_XML\code\dtd\student.dtd">

<!--内部dtd-->
<!--<!DOCTYPE students [-->
<!--        <!ELEMENT students (student*) >-->
<!--        <!ELEMENT student (name,age,sex)>-->
<!--        <!ELEMENT name (#PCDATA)>-->
<!--        <!ELEMENT age (#PCDATA)>-->
<!--        <!ELEMENT sex (#PCDATA)>-->
<!--        <!ATTLIST student number ID #REQUIRED>-->
<!--        ]>-->

<students>
    <student number="s001">
        <name>zhangsan</name>
        <age>23</age>
        <sex>male</sex>
    </student>

    <student number="s002">
        <name>zhangsan</name>
        <age>23</age>
        <sex>male</sex>
    </student>
</students>